stages:
  - test

before_script:
  - . ~/environment_setup  

test:
  stage: test
  script:
    - npm install -f
    - npm test
  tags:
    - k8s
    - linux
  image: 116738426468.dkr.ecr.us-east-2.amazonaws.com/runners/node:nvm-ubuntu    
